[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
  # Single-threaded WASM configuration (no atomics or shared memory)
  "-C", "target-feature=+simd128,+bulk-memory",
  "-C", "opt-level=3",
  "-C", "codegen-units=1"
]
