[build]
# Enable unstable features for better optimization
rustflags = [
    "-C", "target-cpu=native",  # Optimize for the current CPU when building natively
]

# Multi-threaded WASM configuration
[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "opt-level=3",
    "-C", "codegen-units=1",   # Single codegen unit for better optimization
    "--cfg", "web_sys_unstable_apis",  # Enable unstable web APIs
    "-C", "target-feature=+simd128,+bulk-memory",  # Base features for single-threaded
]

# Use wasm-opt for further optimization
runner = "wasm-opt -Os --enable-simd --enable-bulk-memory"

[env]
# Set SIMD and bulk memory features for wasm builds (single-threaded)
RUSTFLAGS_wasm32_unknown_unknown = "-C target-feature=+simd128,+bulk-memory"
# Multi-threaded builds need atomics - override above when building with parallel features

[alias]
# Convenient aliases for development
wasm-build = "build --target wasm32-unknown-unknown --release"
wasm-build-mt = "build --target wasm32-unknown-unknown --release --features wasm-parallel"
wasm-test = "test --target wasm32-unknown-unknown"
wasm-test-mt = "test --target wasm32-unknown-unknown --features wasm-parallel"
bench-native = "bench --workspace --exclude vectorize-wasm"

# Profile for multi-threaded WASM builds
[profile.release-mt]
inherits = "release"
debug = false
lto = true
codegen-units = 1
panic = "abort"