// wasm-bindgen placeholder file
// Auto-generated by rebuild-wasm.js
// Provides stub implementations for wasm-bindgen intrinsic functions
// These are compile-time descriptors that get processed by wasm-bindgen CLI
// They must exist as functions but their actual implementation is handled by the runtime

// Core wasm-bindgen describe functions (compile-time intrinsics)
export function __wbindgen_describe() {}
export function __wbindgen_describe_closure() { return 0; }
export function __wbindgen_describe_cast() { return null; }

// Object reference management
export function __wbindgen_object_clone_ref(idx) { return idx; }
export function __wbindgen_object_drop_ref(idx) {}
export function __wbindgen_object_is_null_or_undefined(idx) { return false; }
export function __wbindgen_object_is_undefined(idx) { return false; }

// String operations
export function __wbindgen_string_new(ptr, len) { return 0; }
export function __wbindgen_string_get(idx) { return null; }

// Number operations
export function __wbindgen_number_new(value) { return 0; }
export function __wbindgen_number_get(idx) { return 0; }
export function __wbindgen_bigint_from_i64(value) { return 0; }
export function __wbindgen_bigint_from_u64(value) { return 0; }

// Boolean operations
export function __wbindgen_boolean_new(value) { return 0; }
export function __wbindgen_boolean_get(idx) { return false; }

// Callback management
export function __wbindgen_cb_drop(idx) { return 0; }
export function __wbindgen_cb_forget(idx) {}

// JSON operations
export function __wbindgen_json_parse(ptr, len) { return 0; }
export function __wbindgen_json_serialize(idx) { return [0, 0]; }

// Type checking
export function __wbindgen_is_undefined(idx) { return false; }
export function __wbindgen_is_null(idx) { return false; }
export function __wbindgen_is_object(idx) { return false; }
export function __wbindgen_is_function(idx) { return false; }
export function __wbindgen_is_string(idx) { return false; }
export function __wbindgen_is_bigint(idx) { return false; }
export function __wbindgen_is_symbol(idx) { return false; }
export function __wbindgen_is_falsy(idx) { return false; }
export function __wbindgen_typeof(idx) { return 0; }

// Memory management
export function __wbindgen_memory() { return { buffer: new ArrayBuffer(0) }; }
export function __wbindgen_throw(ptr, len) { throw new Error('WASM Error'); }
export function __wbindgen_rethrow(idx) {}

// Console functions
export function __wbindgen_console_log(ptr, len) { console.log('WASM Log'); }
export function __wbindgen_console_error(ptr, len) { console.error('WASM Error'); }
export function __wbindgen_console_warn(ptr, len) { console.warn('WASM Warning'); }
export function __wbindgen_console_debug(ptr, len) { console.debug('WASM Debug'); }
export function __wbindgen_console_info(ptr, len) { console.info('WASM Info'); }

// Symbol and iterator support
export function __wbindgen_symbol_new(ptr, len) { return 0; }
export function __wbindgen_symbol_anonymous_new() { return 0; }

// Error handling
export function __wbindgen_error_new(ptr, len) { return 0; }

// Function support
export function __wbindgen_function_table() { return null; }

// Export default for compatibility
export default {};
