// wasm-bindgen placeholder file
// Auto-generated by rebuild-wasm.js
// Provides stub implementations for wasm-bindgen functions

// Core wasm-bindgen functions
export function __wbindgen_describe() { return 0; }
export function __wbindgen_describe_closure() { return 0; }
export function __wbindgen_string_new(ptr, len) { return 0; }
export function __wbindgen_string_get(idx) { return null; }
export function __wbindgen_number_new(value) { return 0; }
export function __wbindgen_number_get(idx) { return 0; }
export function __wbindgen_boolean_new(value) { return 0; }
export function __wbindgen_boolean_get(idx) { return false; }
export function __wbindgen_object_drop_ref(idx) {}
export function __wbindgen_cb_drop(idx) { return 0; }
export function __wbindgen_json_parse(ptr, len) { return 0; }
export function __wbindgen_json_serialize(idx) { return [0, 0]; }
export function __wbindgen_is_undefined(idx) { return false; }
export function __wbindgen_is_null(idx) { return false; }
export function __wbindgen_is_object(idx) { return false; }
export function __wbindgen_is_function(idx) { return false; }
export function __wbindgen_typeof(idx) { return 0; }

// Memory management
export function __wbindgen_memory() { return { buffer: new ArrayBuffer(0) }; }
export function __wbindgen_throw(ptr, len) { throw new Error('WASM Error'); }
export function __wbindgen_rethrow(idx) {}

// Console functions
export function __wbindgen_console_log(ptr, len) { console.log('WASM Log'); }
export function __wbindgen_console_error(ptr, len) { console.error('WASM Error'); }
export function __wbindgen_console_warn(ptr, len) { console.warn('WASM Warning'); }

// Export default for compatibility
export default {};
