name: Minimal CI

on:
  push:
    branches: [main, feature/*]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-minimal.yml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-minimal.yml'

env:
  CI: true
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  minimal-checks:
    name: Minimal CI Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
      
      - name: Run SvelteKit sync
        run: npx svelte-kit sync
      
      - name: Check TypeScript compilation
        run: npx svelte-check --tsconfig ./tsconfig.json
        continue-on-error: true # Don't fail on warnings initially
      
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Verify build output
        run: |
          if [ -d "build" ]; then
            echo "✅ Build successful"
            echo "📊 Build size:"
            du -sh build/ || echo "Could not calculate build size"
          else
            echo "❌ Build failed"
            exit 1
          fi
      
      - name: Run basic smoke test
        run: |
          echo "🧪 Running basic smoke test..."
          # Check that essential files exist
          test -f build/index.html || (echo "❌ Missing index.html" && exit 1)
          echo "✅ Basic smoke test passed"

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [minimal-checks]
    if: always()
    
    steps:
      - name: Check results
        run: |
          if [[ "${{ needs.minimal-checks.result }}" != "success" ]]; then
            echo "❌ Minimal CI checks failed"
            exit 1
          fi
          echo "✅ All minimal checks passed!"