name: Simple E2E Tests

on:
  push:
    branches: [main, feature/*]
    paths:
      - 'frontend/**'
      - '.github/workflows/e2e-simple.yml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/e2e-simple.yml'

env:
  NODE_VERSION: '20'

jobs:
  simple-e2e:
    name: Simple E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
        
      - name: Install Playwright browsers
        run: npx playwright install chromium firefox --with-deps
        
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
        
      - name: Run simple E2E tests
        run: npm run test:simple
        env:
          CI: true
          
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: simple-e2e-results
          path: |
            frontend/playwright-report-simple/
            frontend/test-results/
          retention-days: 7
          
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: simple-e2e-report
          path: frontend/playwright-report-simple/
          retention-days: 3

  summary:
    name: E2E Summary
    runs-on: ubuntu-latest
    needs: [simple-e2e]
    if: always()
    
    steps:
      - name: Check results
        run: |
          echo "Simple E2E Tests: ${{ needs.simple-e2e.result }}"
          
          if [[ "${{ needs.simple-e2e.result }}" != "success" ]]; then
            echo "❌ Simple E2E tests failed"
            exit 1
          fi
          
          echo "✅ All simple E2E tests passed!"